function InvalidDoc(node,source,e,varargin)

switch e
case 'ElementNotFound'
    error(['EtherCATInfo:' source ':ElementNotFound'],...
      ['EtherCAT Info file %s is not valid\n'...
       'Element "%s" (Node index %i) does not have required child "%s"'],...
       char(node.getOwnerDocument.getDocumentURI),...
       char(node.getNodeName),node.getNodeIndex,varargin{1});

case 'RootNotFound'
    error(['EtherCATInfo:' source ':RootNotFound'],...
      ['EtherCAT Info file %s is not valid\n'...
       'Document does not contain root element <EtherCATInfo>'],...
       char(node.getOwnerDocument.getDocumentURI));
    
case 'InvalidHexDecValue'
    error(['EtherCATInfo:' source ':InvalidHexDecValue'],...
      ['EtherCAT Info file %s is not valid\n'...
       'Required HexDecValue in element "%s" (Node index %i) is invalid'],...
       char(node.getOwnerDocument.getDocumentURI), ...
       char(node.getNodeName), node.getNodeIndex);
    
case 'InvalidNumericValue'
    error(['EtherCATInfo:' source ':InvalidHexDecValue'],...
      ['EtherCAT Info file %s is not valid\n'...
       'Required NumericValue in element "%s" (Node index %i) is invalid'],...
       char(node.getOwnerDocument.getDocumentURI), ...
       char(node.getNodeName), node.getNodeIndex);
    
case 'InvalidDataType'
    error(['EtherCATInfo:' source ':InvalidHexDecValue'],...
      ['EtherCAT Info file %s is not valid\n'...
       'DataType "%s" in element "%s" (Node index %i) is unknown'],...
       char(node.getOwnerDocument.getDocumentURI), ...
       char(varargin{1}), char(node.getNodeName), node.getNodeIndex);

case 'IncompatibleDataType'
    error(['EtherCATInfo:' source ':InvalidHexDecValue'],...
      ['EtherCAT Info file %s is not valid\n'...
       'DataType "%s" in element "%s" (Node index %i) '...
       'has %i bits, whereas the PdoEntry has %i bits'],...
       char(node.getOwnerDocument.getDocumentURI), ...
       char(varargin{1}), char(node.getNodeName), node.getNodeIndex,...
       varargin{2}, varargin{3});

case 'InvalidAttr'
    error(['EtherCATInfo:' source ':InvalidHexDecValue'],...
      ['EtherCAT Info file %s is not valid\n'...
       'Required attribute "%s" in element "%s" (Node index %i) is '...
       'either missing or does not evaluate to a number'],...
       char(node.getOwnerDocument.getDocumentURI), ...
       char(varargin{1}), char(node.getNodeName), node.getNodeIndex);
    
otherwise
    error(['EtherCATInfo:' source ':Unknown'],...
    ['EtherCAT Info file %s is not valid\n'...
     'Unknown error %s on element "%s" (Node index %i)'],...
     char(node.getOwnerDocument.getDocumentURI),...
     e.type,char(node.getNodeName),node.getNodeIndex);
end
