
EXTRA_CFLAGS := -Wall $(DEFS) -I$(M)/../.. -I$(M)/../../tools/include

EXTRA_CFLAGS += $(shell \
        DESTDIR=$(STAGING_DIR) $(STAGING_DIR)/$(RTAI_DIR)/bin/rtai-config \
                --module-cflags)

EXTRA_SYMBOLS := $(RTAI_DIR)/include/Module.symvers

obj-m        := rt_kernel.o rt_test.o
rt_kernel-y  := $(RT_KERNEL_SRCS:.c=.o)
rt_test-y    := test_vars.o

clean-files := $(obj)/kernel-cflags.c

hostprogs-y := kernel-cflags
always      := $(hostprogs-y)

$(obj)/kernel-cflags.c:
	@echo -e "#include <stdio.h>\n \
                  int main(void) { printf(\"%s\\\\n\", \
                  \"$(CFLAGS)\"); return 0; }" > $@
