#!/usr/bin/env python

import zlib
import sys

if len(sys.argv) < 3:
    print """
usage: %s <shared object> <model symbol file>
""" % sys.argv[0]
    sys.exit(0)

f = open(sys.argv[1])
z = zlib.compress(f.read())

g = open(sys.argv[2], 'w')

g.write("""/* Model symbol file
 *
 * The string below contains a compressed version of the shared object that
 * that describes the model with all its signals.
 * This string is unpacked and loaded by the buddy to be able to interpret
 * the data that is sent by the real time process 
 * 
 * Generated by: 
 * $Id$
 * 
 */

#include "mdf.h"

const char model_symbols[] =
""")

for i in xrange(len(z)):
    if not i % 16: 
        if i:
            g.write('\"\n')
        g.write('\t\"')
    g.write('\\x%02x' % ord(z[i]))
g.write('";\n\n')
g.write(
  'size_t model_symbol_len = sizeof(model_symbols)-1; /* %u */\n' 
  % len(z)
)
