/*
 * File: taskinfo.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Sat Jan 14 22:13:16 2006
 * 
 *
 */


#define S_FUNCTION_NAME taskinfo
#define S_FUNCTION_LEVEL 2
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS           0

#define NUM_OUTPUTS          4
/* Output Port  0 */
#define OUT_PORT_0_NAME      WorldTime
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      ExecutionTime
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME      dT
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME      OverrunCount
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125

#define NPARAMS              1

#define SAMPLE_TIME_0        PARAM_DEF0(S)
#define NUM_DISC_STATES      4  /* 0: Average of input time steps
                                 * 1: Discrete time step ZOH
                                 * 2: dT Integrator
                                 * 3: T Integrator
                                 */
#define DISC_STATES_IC       [0,1.0,0]
#define NUM_CONT_STATES      0
#define CONT_STATES_IC       [0]
#define NUM_R_WORK           4  /* 0: new World Time in [s]
                                 * 1: old World Time
                                 * 2: k_p
                                 * 3: k_i
                                 */
#define NUM_I_WORK           1  /* Counts of new World Time */

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB____SFB__"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   1                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define TSAMPLE  (mxGetScalar(PARAM_DEF0(S)))

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

/* Characteristics of second order filter that will be used to track the
 * world time
 * OMEGA is still further dynamically modified by the incoming frequency 
 * of world time stamps
 */
#define DAMPING (1.000)
#define OMEGA   (0.1)
#define TIMESTEP_WEIGHT (0.1)


/*====================*
 * S-function methods *
 *====================*/
static void mdlInitializeSizes(SimStruct *S)
{
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
    #if defined(MATLAB_MEX_FILE)
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
       return; /* Parameter mismatch will be reported by Simulink */
     }
    #endif

    ssSetSFcnParamTunable(S,0,0);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, NUM_R_WORK);
    ssSetNumIWork(S, NUM_I_WORK);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, TSAMPLE);
    ssSetOffsetTime(S, 0, 0.0);
}
#define MDL_INITIALIZE_CONDITIONS
 /* Function: mdlInitializeConditions ========================================
  * Abstract:
  *    Initialize the states
  */
  static void mdlInitializeConditions(SimStruct *S)
  {
   
    real_T *xD   = ssGetDiscStates(S);
    int_T   *iWork     =  (int_T *)ssGetIWork(S);
    real_T  *rWork     = (real_T *)ssGetRWork(S);
   
    rWork[0] = 0.0;
    rWork[1] = 0.0;
    rWork[2] = 0.0;
    rWork[3] = 0.0;

    iWork[0] = (int_T)1/TIMESTEP_WEIGHT;

    xD[0] = 0.0;
    xD[1] = 0.0;
    xD[2] = 1.0;               /* First estimate of time ramp */
    xD[3] = 0.0;
  }
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
   ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    real_T  *WorldTime = ssGetOutputPortRealSignal(S,0);
    real_T  *ExecTime  = ssGetOutputPortRealSignal(S,1);
    real_T  *dT        = ssGetOutputPortRealSignal(S,2);
    real_T  *overrun   = ssGetOutputPortRealSignal(S,3);
    real_T  *xD        = ssGetDiscStates(S);
    real_T  *rWork     = ssGetRWork(S);
    int_T   *iWork     = ssGetIWork(S);
    static int i = 100;

    *WorldTime = xD[3];

    /* The other outputs are misused in the MEX version (it is different
     * in TLC) to output internal states
     */
    *ExecTime  = xD[1];
    *dT        = rWork[0];
    *overrun   = xD[2];

    if (i++ == 100) {
        rWork[0] = ssGetT(S)+1.0;
        i = 0;
    }

    if (rWork[0] != rWork[1]) {
        real_T   weight = TIMESTEP_WEIGHT, /* Weighting factor for time jump */
                 w;             /* filters natural freq */

        /* Input time changed */
        if (iWork[0]) {
            iWork[0]--;
            weight = 1.0/(1/TIMESTEP_WEIGHT - iWork[0]);
        }

        /* Make a sliding average of input time steps, weighting the change
         * from 1 to 0.1 for the first 10 changes, thereafter keeping 0.1
         * xD[0] then is the average of the time jumps this system sees.
         */
        xD[0] = (1 - weight)*xD[0] 
            + weight*(rWork[0] - rWork[1]);
        rWork[1] = rWork[0];

        /* Make filter cutoff frequency 1/10th of time jump frequency */
        w = OMEGA/xD[0];
        rWork[2] = 2*DAMPING*w;
        rWork[3] = w*w;

        /* Work out the error of WorldTime - myTime */
        xD[1] = rWork[0] - xD[3];
    }
}

#define MDL_UPDATE
/* Function: mdlUpdate =======================================================
 *
*/
static void mdlUpdate(SimStruct *S, int_T tid)
{
    real_T  *rWork     = ssGetRWork(S);
    real_T  *xD        = ssGetDiscStates(S);

    xD[3] += TSAMPLE*(rWork[2]*xD[1] + xD[2]);
    xD[2] += TSAMPLE*rWork[3]*xD[1];
}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}

#define MDL_RTW
static void mdlRTW(SimStruct *S)
{
    real_T Ts = TSAMPLE;
    real_T omega = OMEGA;
    real_T damping = DAMPING;
    real_T weight = TIMESTEP_WEIGHT; /* Weighting factor for time jump */

    if (!ssWriteRTWWorkVect(S, "RWork", 4, 
                "WorldTime", 1,
                "oldWorldTime", 1,
                "k_p", 1,
                "k_i", 1
                ))
        return;
    if (!ssWriteRTWScalarParam(S, "Omega", &omega, SS_DOUBLE))
        return;
    if (!ssWriteRTWScalarParam(S, "Weight", &weight, SS_DOUBLE))
        return;
    if (!ssWriteRTWScalarParam(S, "Damping", &damping, SS_DOUBLE))
        return;
    if (!ssWriteRTWScalarParam(S, "Ts", &Ts, SS_DOUBLE))
        return;


}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


