EXTRA_CFLAGS := $(DEFS) -I$(M)/../.. -I$(M)/../../tools/include \
	-I$(STAGING_DIR)/$(PREFIX)/include

EXTRA_CFLAGS += $(shell \
        DESTDIR=$(STAGING_DIR) $(STAGING_DIR)/$(RTAI_DIR)/bin/rtai-config \
                --module-cflags)

obj-m   := $(TGT)
