EXTRA_CFLAGS := $(DEFS) -I$(M)/../.. -I$(M)/../../tools/include \
	-I$(PREFIX)/include

EXTRA_CFLAGS += $(shell \
        DESTDIR=$(STAGING_DIR) $(STAGING_DIR)/$(RTAI_DIR)/bin/rtai-config \
                --module-cflags)

obj-m   := raise_catch.o

ifneq ($(wildcard $(PREFIX)/include/ecrt.h),)
obj-m   +=  ecrt_support.o
endif
