function setup()

disp(['Precompiling XML files in ' pwd]);

file = {...
 'Beckhoff EKxxxx.xml', 'EtherCATInfo_ekxxxx'; ...
 'Beckhoff EL1xxx.xml', 'EtherCATInfo_el1xxx'; ...
 'Beckhoff EL15xx.xml', 'EtherCATInfo_el15xx'; ...
 'Beckhoff EL2xxx.xml', 'EtherCATInfo_el2xxx'; ...
 'Beckhoff EL3xxx.xml', 'EtherCATInfo_el3xxx'; ...
 'Beckhoff EL30xx.xml', 'EtherCATInfo_el30xx'; ...
 'Beckhoff EL31xx.xml', 'EtherCATInfo_el31xx'; ...
 'Beckhoff EL37xx.xml', 'EtherCATInfo_el37xx'; ...
 'Beckhoff EP3xxx.xml', 'EtherCATInfo_ep3xxx'; ...
 'Beckhoff EP4xxx.xml', 'EtherCATInfo_ep4xxx'; ...
 'Beckhoff EL47xx.xml', 'EtherCATInfo_el47xx'; ...
 'Beckhoff EL5xxx.xml', 'EtherCATInfo_el5xxx'; ...
 'Beckhoff EL7xxx.xml', 'EtherCATInfo_el7xxx'; ...
 'Beckhoff EL9xxx.xml', 'EtherCATInfo_el9xxx'; ...
 'BaumerThalheim_ECAT_Encoders512Bytes_02.05.04.xml', 'EtherCATInfo_baumerecatencoder'; ...
 'ESD-ethercat-can.xml', 'EtherCATInfo_esdcan'; ...
 'Murrelektronik_IMPACT67.xml', 'EtherCATInfo_murrimpact67'; ...
 'MTS.xml'            , 'EtherCATInfo_mts'   };

for i = 1:size(file,1)
  fprintf('Precompiling ''%s'' ... ', file{i,1});
  str = [file{i,2} ' = EtherCATInfo(''' file{i,1} ''');'];
  eval(str);
  save( ['../' file{i,2}], file{i,2} )
  fprintf('done\n');
end
    
% Old version of EL4132 is missing. Add it manually
fprintf('Precompiling ''%s'' ... ', 'Beckhoff EL4xxx.xml');
EtherCATInfo_el4xxx = EtherCATInfo('Beckhoff EL4xxx.xml');
EtherCATInfo_el4102 = EtherCATInfo('EL4102-mod.xml');
EtherCATInfo_el4xxx = appendDevice(EtherCATInfo_el4xxx,EtherCATInfo_el4102);
EtherCATInfo_el4132 = EtherCATInfo('EL4132-mod.xml');
EtherCATInfo_el4xxx = appendDevice(EtherCATInfo_el4xxx,EtherCATInfo_el4132);
save('../EtherCATInfo_el4xxx', 'EtherCATInfo_el4xxx');
fprintf('done\n');

return
