/* Model data header file
 *
 * This file defines data structures that define the model's signals and parameters.
 * 
 * Do not edit this file, its was automatically generated from:
 * model_data.xml
 * 
 * Generated by: 
 * $Id$
 * 
 */

#include "model_defines.h"

/* Model signals */
struct rtB {
  double var1[10];
  double var2;
};

/* Model parameters */
struct rtP {
  double param1[10];
};
