/* Model symbol file
 *
 * The string below contains a compressed version of the shared object that
 * that describes the model with all its signals.
 * This string is unpacked and loaded by the buddy to be able to interpret
 * the data that is sent by the real time process 
 * 
 * Generated by: 
 * $Id$
 * 
 */

#include "msf.h"

typedef struct {
  double var1[10];
  double var2;
} rtB;

typedef struct {
} rtP;
